/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package othello;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    
    @Test
    void ReplacePieceTest() {
        Board board = new Board();

        board.ReplacePiece(Space.White, 1, 1);
        assertEquals(board.getPiece(1, 1), Space.White);
    }
}
