/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package othello

import spock.lang.Specification

class Basic extends Specification {
    def "Tie game"() {
        setup:
        def game = new Game()
        
        when:
        game.CalculateWinner()
        def result = game.GetWinner()
        
        then:
        result == Space.None;
    }
}
